# Generated by Django 2.2 on 2019-07-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=100)),
                ('department_leader', models.CharField(max_length=100)),
                ('establish_date', models.CharField(max_length=100)),
                ('department_label', models.CharField(blank=True, max_length=100)),
                ('parent_id', models.IntegerField()),
            ],
            options={
                'verbose_name': '部门管理',
                'verbose_name_plural': '部门管理',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '小组管理',
                'verbose_name_plural': '小组管理',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '岗位管理',
                'verbose_name_plural': '岗位管理',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityId', models.IntegerField()),
                ('authorityName', models.CharField(max_length=100)),
                ('menuUrl', models.CharField(blank=True, max_length=100)),
                ('menuIcon', models.CharField(blank=True, default='layui-icon-set', max_length=100)),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('isMenu', models.IntegerField()),
                ('parentId', models.IntegerField()),
            ],
            options={
                'verbose_name': '菜单管理',
                'verbose_name_plural': '菜单管理',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '角色管理',
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateField(auto_now_add=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('job_status', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('superior', models.CharField(max_length=100)),
                ('administration', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
