# Generated by Django 2.2 on 2019-07-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='group',
            new_name='jobs_name',
        ),
    ]
