# Generated by Django 2.2 on 2019-07-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_auto_20190727_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='locking',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
