# Generated by Django 2.2 on 2019-07-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='checked',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_power',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.CharField(max_length=100),
        ),
    ]
