# Generated by Django 2.2 on 2019-07-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_auto_20190720_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_icon',
            new_name='menuIcon',
        ),
    ]
