# Generated by Django 2.2 on 2019-07-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0003_sysuser_locking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='locking',
            field=models.IntegerField(default=0),
        ),
    ]
