# Generated by Django 2.2 on 2019-07-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0008_auto_20190721_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='orderNumber',
        ),
    ]
