# Generated by Django 2.2 on 2019-07-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0009_auto_20190721_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='checked',
            field=models.IntegerField(default=0),
        ),
    ]
