# Generated by Django 2.2 on 2019-07-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0010_menu_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='orderNumber',
            field=models.IntegerField(default=1),
        ),
    ]
