# Generated by Django 2.2 on 2019-07-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0012_auto_20190721_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuIcon',
            field=models.CharField(blank=True, default='layui-icon-set', max_length=100),
        ),
    ]
