# Generated by Django 2.2 on 2019-07-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0013_auto_20190721_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityId', models.IntegerField()),
                ('authorityName', models.CharField(max_length=100)),
                ('menuUrl', models.CharField(blank=True, max_length=100)),
                ('menuIcon', models.CharField(blank=True, default='layui-icon-set', max_length=100)),
                ('authority', models.CharField(blank=True, max_length=100)),
                ('isMenu', models.IntegerField()),
                ('parentId', models.IntegerField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': '菜单管理',
                'verbose_name_plural': '菜单管理',
            },
        ),
    ]
