# Generated by Django 2.0.6 on 2019-07-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0014_menunew'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_id', models.IntegerField()),
                ('department_name', models.CharField(max_length=100)),
                ('department_leader', models.CharField(max_length=100)),
                ('establish_date', models.CharField(max_length=100)),
                ('department_label', models.CharField(blank=True, max_length=100)),
                ('parentId', models.IntegerField()),
            ],
            options={
                'verbose_name': '部门管理',
                'verbose_name_plural': '部门管理',
            },
        ),
        migrations.DeleteModel(
            name='MenuNew',
        ),
    ]
