# Generated by Django 2.0.6 on 2019-07-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0015_auto_20190724_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentinfo',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
