# Generated by Django 2.0.6 on 2019-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0016_auto_20190724_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '小组管理',
                'verbose_name_plural': '小组管理',
            },
        ),
    ]
